### ISSUE TITLE
<!DOCTYPE html> not rendered

### ISSUE THREAD

**Issue by jsoques** [basxsoftwareassociation/htmlgenerator#12]
Hello, trying the simple example , the `<!DOCTYPE html>` is not being rendered. Is there something else that has to be set? Thanks.

**Comment by saemideluxe** [comment]
Hi

Right, I changed the default behaviour at some point, for some reason and did not update the README. You need to pass `doctype=True` to the `HTML` element, like `hg.HTML(...... , doctype=True)`. Updated the README accordingly.

**Comment by jsoques** [comment]
Thanks.
